### PR TITLE
[PreventAD-open_v20.1] Latest import scripts from John's PR

### PR DESCRIPTION
**Pull request by maltheism**
**Note:** The code was taken from https://github.com/aces/Loris/pull/5334

Copying original PR notes:

## Brief summary of changes

This script was originally written for the use of getting a subset of PreventAD data from its instance into a new "Open Science" instance. It has been thoroughly reviewed and tested by @Jkat and @cmadjar. 

I'm pushing this to the main repo as @samirdas mentioned that it should go here. It's probable that other projects in the future will need something similar and may benefit from this script.

Further background and detail can be found in the discussion on the original PR on my LORIS fork: https://github.com/johnsaigle/Loris/pull/15

The original PR description follows.

---

This pair of scripts allows one to export data from one database and import it another database, mapping PSCIDs from the former to new values. This allows for a way of transferring data into e.g. an Open Science database while giving the candidates new identifier to preserve privacy between databases.

## Data Extraction
The dataExtractor.php script is used to extract data from the source database. It can extract data from either the candidate table, the session table, or from tables containing instrument data. Other tables are unsupported and the behaviour of this script when trying to extract data from other tables is undefined/almost guaranteed to have bugs.

The script writes data to project/data_export/ in CSV format. Optionally can be written elsewhere.

## Data Import
The openScienceDataImport.php script is used to import data. It takes several parameters:

An operation mode, either 'candidate', 'visits', or 'instrument', corresponding to the dataExtractor tool
A CSV file mapping old/source PSCIDs to a new PSCID and new CandID for the destination database.
A source data file generated by dataExtractor.php. This file should not be renamed as the name of the MySQL table to update will be included in the name
It analyzes the two CSV files and generates SQL commands, either INSERT or UPDATE, that can be used to insert the data into the database. These commands are written to a file in project/data_import/ with a timestamp.

Candidate information will always be UPDATE statements as the candidates are expected to be created in the candidate table beforehand.
Visits information will be a mix of UPDATE or INSERT depending on whether the visit label exists
Instrument information will always be INSERTs as it is expected that instrument information is not yet populated in the DB.

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@maltheism could you remove the changes made to `test/run-php-linter.sh`? I don't think they are related to the scripts.

Also, could you maybe rename the old tools script in the tools directory that John had in the tools directory directly? Don't want to delete them quite yet just in case. They could be renamed something like `tools/DataImporter_release_1_2019_version.php`.

Thanks!

**Comment by maltheism** [comment]
Hi @cmadjar, I reverted the `test/run-php-linter.sh` change. I think renaming isn't needed because the new files are in the exporters & importers directories.

**Comment by cmadjar** [comment]
@maltheism the renaming suggestion was to be sure we do not use the wrong php script even though they are not in the same folder. Once we know for sure that the new scripts work well, we will remove them completely to avoid any confusion. Does that make sense? Thanks!

**Comment by maltheism** [comment]
@cmadjar so I should rename the newer files or the older? Cause then I think I may have to go into the code and refactor the names/paths as well?

**Comment by cmadjar** [comment]
I was thinking of renaming the old ones as back up ones and keep the new code from John as is until it is tested.

**Comment by maltheism** [comment]
@cmadjar the old files have been renamed.

**Review by cmadjar — APPROVED** [review]
👍 Thank you @maltheism!

**Pull request merged**
